import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

import "remixicon/fonts/remixicon.css";
import Footer from "@/components/Footer";
import ScrollToTop from "@/components/ScrollToTop";

const fontPoppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Profile Bussines",
  description: "Generated by rizaldhmarsa",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${fontPoppins.className} antialiased`} id="beranda">
        <ScrollToTop />
        <Navbar />
        <div className="container mx-auto px-4">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
